### ISSUE TITLE
RepoSense error in LoC

### ISSUE THREAD

**Issue by Tejas2805** [AY1920S2-CS2103T-F11-1/main#170]
Hey guys,

I think you guys told your tutor regarding some issue in RepoSense's calculation of LoC. Can you guys give more details?

**Comment by thrivinb** [comment]
Our LoC, in general, suddenly dropped this week from last week. May we know why is this the case? Also, the code I have pushed (@buddhavineeth) the past 3 days is not being reflected in RepoSense.

**Comment by Tejas2805** [comment]
Which commit is this? Please send a link. From my check, up-to-the last build of the RepoSense all commits are there.

**Comment by thrivinb** [comment]
Dear Tejas, just checked again and am glad the RepoSense report is updated now! Thank you. However, my team is still curious (not overly concerned) about what changed over the last week because each of our LoC decreased by a non-trivial amount.
